### ISSUE TITLE
Add original greek/hebrew texts (sblgnt)

### ISSUE THREAD

**Issue by danbenn** [STEPBible/BibleEngine#104]

**Comment by chriswep** [comment]
i'm thinking that we should integrate the greek text within it's own schema to make use of the related dataset. doing that we can dynamically show the different variants and also implement a cross-linking of strong-keyed versions to the greek text on the core level. If you agree, we can track this on the existing issue here: https://github.com/tyndale/BibleEngine/issues/8

**Comment by danbenn** [comment]
ok.

@chriswep thats a much more involved task, I think for now I'll just use my OSIS parser to parse the SBLGNT and translator's hebrew old testament, and put them on my BibleEngine server

That way, people can get at least get the texts with strongs popups for now 👍 

does that sound ok?

**Comment by chriswep** [comment]
@danbenn  of course you can add those versions, in the end they are technically not different than any other translation.

thinking about a more high-level vision for BibleEngine i'd say that #8 is what could really distinguish this project from others, in that the original languages are really at the heart of it and not just additional versions. in the longterm i see `BibleEngine` with the original text being the "engine", where you can add translations on top that connect and interact with it and get automatic strongs, morphology and interlinear (with the help of a lot of magic from @DavidIB) even for untagged versions.

**Comment by danbenn** [comment]
Thats brilliant, @chriswep ! I'd love to help, is there anything I can do to contribute?

A granular list of steps for, "this is how we get there" would be cool!

How to execute the big picture is over my head, but smaller tasks I could do

**Comment by chriswep** [comment]
@danbenn reading through #8 would be a start. first step would be to agree with @DavidIB on what data-source we should use for bibleengine (the public one on stepdata or the internal one) and then define a schema for it. This schema should be indexed for every strong, every morphology code, obviously for phraseId/refId and also textSource. if we have that, we can start "harvesting" the data by adding all kinds of methods to bibleEngine.core.

one method would need to be written to compile a document-object for reading, since the default one can't be used then (at least not all of it).

concerning reading original texts in the app i would envision to make a separate switch in the UI that switches the text to original. its more ui than a technical reason, but would highlight the nature of the app. however there probably will be a slightly different UI for the original text display since it can be filtered for the different text versions.

Let me know if you have specific questions. if you want to go for that instead of adding the texts as just versions i suggest to continue on #8 in favour of this issue.
