### ISSUE TITLE
As an app user, I want to see every use of a Strongs word across the Bible, to better understand context of word

### ISSUE THREAD

**Issue by danbenn** [STEPBible/BibleEngine#148]

**Comment by chriswep** [comment]
@danbenn  answering via the original issue #40 

> Would especially love to add, "search for all instances of that same word", but can't until the metadata stuff is added
> @chriswep , when we talked about this, there was something missing that made it hard / impossible to find all instances of a Strongs word across the text, right?

we decided to save the strong in the phrase entity and not in a separate relation-table to save space and to optimise for the main use case. since there can be more than one strong for one phrase you can't easily query for all instances of one single strong. however adding an index on the `strongs` column and querying for the exact same content for any given phrase might lead to sufficient results.

The intended way for this to be done is by using the actual "core" data of BibleEngine, which is original language dataset that includes all the detailed information along with it (and has single-word-only entities). however this still has to be included.

**Comment by danbenn** [comment]
ok, I see
